if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

alias gss=gws
alias gs=''
alias gd=gwd
alias gdc=gid
alias sync!='git pull --rebase origin develop'
alias fetch='git remote update origin --prune'

if [ -n "$TMUX" ]; then
  alias cdd="cd $(tmux show-environment -g PWD | sed 's/PWD=//g')"
fi

alias gpush='git push origin $(git-branch-current)'
_VIM=$(which vim)
alias vim!=$_VIM
alias vim='echo "Use e to edit"'
