export LC_ALL="en_US.UTF-8"
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

alias gss=gws
alias gs=''
alias gd=gwd
alias gdc=gid
alias sync!='git pull --rebase origin develop'
alias fetch='git remote update origin --prune'

alias gpush='git push origin $(git-branch-current)'
alias be='bundle exec'
alias sync!='git pull --rebase origin $(git config --get gitflow.branch.develop || echo "develop")'
alias bump!='vim VERSION && git commit -m "Bump version" VERSION'

ssh() {
  if [ -n "$TMUX" ]; then
    tmux rename-window -t${TMUX_PANE} "@$1"
  fi;

  command ssh ubuntu@$1

  if [ -n "$TMUX" ]; then
    tmux rename-window -t${TMUX_PANE} "zsh"
  fi;
}

alias ssh!='command ssh'
alias ghh='git flow hotfix'
